### ISSUE TITLE
EthToGodwokenAddr.convert returns wrong address

### ISSUE THREAD

**Issue by Kuzirashi** [nervosnetwork/godwoken-polyjuice#116]
## Problem

Demo and readme: https://github.com/Kuzirashi/eth-to-godwoken-address

Result:

```
➜  eth-to-godwoken-address git:(master) ✗ node index.js EthToGodwokenAddr.json 
Found file: ./build/contracts/EthToGodwokenAddr.json
{ shortAddressExpected: '0x8016dcd1af7c8cceda53e4d2d2cd4e2924e245b6' }
Deploying contract...
Deployed contract address: 0xAe2A293A0E7eF59560A655B08101c34b57C29fc9
{ result: '0xF2FDEc7Bb197CA750193611628Af43CA7E679FA0' }
/home/kuzi/projects/eth-to-godwoken-address/index.js:80
        throw new Error(`Contract returns incorrect address. Expected: "${shortAddressExpected}". Received: "${result}".`);
              ^

Error: Contract returns incorrect address. Expected: "0x8016dcd1af7c8cceda53e4d2d2cd4e2924e245b6". Received: "0xF2FDEc7Bb197CA750193611628Af43CA7E679FA0".
    at /home/kuzi/projects/eth-to-godwoken-address/index.js:80:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Contract (not working):
```
pragma solidity >=0.6.0 <=0.8.2;

contract EthToGodwokenAddr {
    function convert(address eth_addr) public returns (address) {
        uint256[1] memory input;
        input[0] = uint256(uint160(address(eth_addr)));
        uint256[1] memory output;
        assembly {
            if iszero(call(not(0), 0xf3, 0x0, input, 0x20, output, 0x20)) {
                revert(0x0, 0x0)
            }
        }
        return address(uint160(output[0]));
    }
}
```

For ETH address: 0xD173313A51f8fc37BcF67569b463abd89d81844f, expected Godwoken address: 0x8016dcd1af7c8cceda53e4d2d2cd4e2924e245b6 (correct), actual (from Solidity): 0xF2FDEc7Bb197CA750193611628Af43CA7E679FA0 (wrong)

I'm using the same Solidity contract code as recommended in docs and in tests in this repository.

## Context

I need this because I'm deploying Gnosis Safe on Godwoken Testnet and I need ability for conversion between Ethereum <-> Godwoken addresses to make sure Multisig is working fine.

![image](https://user-images.githubusercontent.com/4950658/150700908-14c0a874-518f-40a9-8cde-d032f2ec267f.png)

cc @Flouse

**Comment by jjyr** [comment]
https://github.com/honestgoing/godwoken-polyjuice-compatibility-examples/blob/main/scripts/multi-sign-wallet.ts

Can you compare the code with this example?
