### ISSUE TITLE
SUDT-proxied ckETH transfer fails on testnet

### ISSUE THREAD

**Issue by Kuzirashi** [nervosnetwork/godwoken-polyjuice#82]
Demo repository: https://github.com/Kuzirashi/polyjuice-sudt-proxy-transfer

Expected: User A is able to send his proxied ckETH through SUDT-proxy contract to user B on Layer 2.

Result:
Can't send transfer.

Output:
```
➜ node transfer.js
Testing ckETH SUDT proxy transfer on Nervos Layer 2 Testnet
Using Ethereum address: 0xd46aC0Bc23dB5e8AfDAAB9Ad35E9A3bA05E092E8
Deploying SUDT Proxy contract...
Deploy transaction hash: 0xb2f3d8a8ec6b9e8ac40a67fd0f7046dd2ef43caaf352f88e4a6376f2f4a474e6
Deployed SUDT-ERC20 Proxy contract address: 0x0Af214B26c6CF6af293B6378a6719d2f927DfD49
Corresponding Sender Polyjuice address: 0x56eaccaa2ce59c6c0400b1e0b2e70dfd2dddd166
Checking ckETH balance...
Sender ckETH balance before transfer:  776999000000000000
Receiver ckETH balance before transfer:  0
Try calling transfer before sending...
Can't call transfer method. Error.
Error: Returned error: {"jsonrpc":"2.0","id":8,"error":"invalid exit code 2"}
    at Object.ErrorResponse (/home/kuzi/projects/polyjuice-sudt-proxy-transfer/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /home/kuzi/projects/polyjuice-sudt-proxy-transfer/node_modules/web3-core-requestmanager/lib/index.js:303:36
    at PolyjuiceHttpProvider.send (/home/kuzi/projects/polyjuice-sudt-proxy-transfer/node_modules/@polyjuice-provider/web3/lib/providers.js:160:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  data: null
}
Try sending ckETH transfer...
# <STUCK - NEVER COMPLETES> <==========
```

**Comment by haxyz** [comment]
As #81 is showing, my tests were pointing exactly to this: my contracts run fine with [testERC20](https://github.com/haxyz/sisyphus-gamble-v1-tests/blob/master/contracts/testERC20.sol) but not with SUDT-proxied ckETH.

**Comment by Flouse** [comment]
The new version of Polyjuice with `SudtERC20Proxy_UserDefinedDecimals.sol` is not yet deployed on testnet.

@Kuzirashi 
Is that OK on your local devnet?

**Comment by Kuzirashi** [comment]
@Flouse 

Let me create normal SUDT version as new branch and report back.

**Comment by Kuzirashi** [comment]
@Flouse 

Standard SUDT contract doesn't work on testnet as well, same problem. Branch with reproduction: https://github.com/Kuzirashi/polyjuice-sudt-proxy-transfer/tree/standard-sudt

**Comment by Flouse** [comment]
For security reason, we should only use [this SudtERC20Proxy bytecode](https://github.com/nervosnetwork/godwoken-polyjuice/blob/2ac22c50aaae5b004cee481296e42552b7f907ba/solidity/erc20/SudtERC20Proxy.bin) which code hash will be checked in `transfer_to_any_sudt` pre-compiled contract.

> https://github.com/Kuzirashi/polyjuice-sudt-proxy-transfer/tree/standard-sudt

So, in this demo, we should use [this SudtERC20Proxy bytecode](https://github.com/nervosnetwork/godwoken-polyjuice/blob/2ac22c50aaae5b004cee481296e42552b7f907ba/solidity/erc20/SudtERC20Proxy.bin) to replace the `bytecode` in build/contracts/ERC20.json.

---

We will add some docs to make this more clear.

**Comment by Kuzirashi** [comment]
Fixed by using provided bytecode. :) Transfer works.

```
➜ node transfer.js
Testing ckETH SUDT proxy transfer on Nervos Layer 2 Testnet
Using Ethereum address: 0xd46aC0Bc23dB5e8AfDAAB9Ad35E9A3bA05E092E8
Deploying SUDT Proxy contract...
Deploy transaction hash: 0x9254a0ed95352cc90309c24dc176b9262b903646e814bd0382b5b0e3a23eabcd
Deployed SUDT-ERC20 Proxy contract address: 0x84220609e42b51c9aEf056Da0A06983746974291
Corresponding Sender Polyjuice address: 0x56eaccaa2ce59c6c0400b1e0b2e70dfd2dddd166
Checking ckETH balance...
Sender ckETH balance before transfer:  776999000000000000
Receiver ckETH balance before transfer:  0
Try calling transfer before sending...
Try sending ckETH transfer...
Sender ckETH balance after transfer:  776998999999999000
Receiver ckETH balance after transfer:  1000
```
