### ISSUE TITLE
Return revert reasons when errors are encountered

### ISSUE THREAD

**Issue by Kuzirashi** [nervosnetwork/godwoken-polyjuice#94]
![image](https://user-images.githubusercontent.com/4950658/135892996-cdc70962-124d-4c78-8954-a450e3f5b411.png)

Expected:
- When revert in a smart contract happens with a revert reason string, polyjuice-provider should handle it like Ethereum does.

Actual:
- Revert reason isn't visible.

Code that should be working:
- Hardhat tests expect.to.be.revertedWith

Example:
```
it('require fail - voting period too low', async function() { 
      expect(baal.submitProposal(
        proposal.flag,
        deploymentConfig.MIN_VOTING_PERIOD_IN_SECONDS - 100,
        [proposal.account], 
        [proposal.value],
        [proposal.data],
        ethers.utils.id(proposal.details)
      )).to.be.revertedWith(revertMessages.submitProposalVotingPeriod);
    });
```

**Comment by Flouse** [comment]
- https://github.com/nervosnetwork/godwoken/pull/377

**Comment by Flouse** [comment]
> * https://github.com/nervosnetwork/godwoken-polyjuice/pull/95
> * https://github.com/nervosnetwork/godwoken/pull/377
> * https://github.com/nervosnetwork/godwoken-web3/pull/75

The [godwoken-docker-prebuilds v0.6.9-rc1](https://hub.docker.com/layers/nervos/godwoken-prebuilds/v0.6.9-rc1/images/sha256-4de8f53fc54cdc62b019384ffa53fbe7f76378b82ed3f9b0598932795a75e63a?context=explore) image has included these 3 PRs.
- https://github.com/nervosnetwork/godwoken-docker-prebuilds/blob/v0.6.9-rc1/Makefile#L9-L13
